// Day-based streak milestone badges (as opposed to ACTIVITY_BADGE_DEFS-style
// achievement badges like first_payment/loss_first_log/goal_set, which live
// in the same `badges` table but aren't "milestones" in the streak sense).
// Exported so any screen counting/filtering milestone badges (e.g. account.tsx's
// "Milestones" stat) uses the same list index.tsx awards from — otherwise counts
// drift whenever a non-milestone achievement badge is also in the table.
export const BADGE_DEFS = [
  { type: 'started',    emoji: '🚀', label: 'Started',    days: 0 },
  { type: '1_hour',     emoji: '⏰', label: '1 Hour',     days: 1/24 },
  { type: '3_hours',    emoji: '🌤️', label: '3 Hours',    days: 3/24 },
  { type: '6_hours',    emoji: '☀️', label: '6 Hours',    days: 6/24 },
  { type: '12_hours',   emoji: '🌗', label: '12 Hours',   days: 12/24 },
  { type: '1_day',      emoji: '🌱', label: '1 Day',      days: 1 },
  { type: '3_days',     emoji: '🌿', label: '3 Days',     days: 3 },
  { type: '5_days',     emoji: '🕊️', label: '5 Days',     days: 5 },
  { type: '1_week',     emoji: '⭐', label: '1 Week',     days: 7 },
  { type: '10_days',    emoji: '✨', label: '10 Days',    days: 10 },
  { type: '2_weeks',    emoji: '🌙', label: '2 Weeks',    days: 14 },
  { type: '3_weeks',    emoji: '💫', label: '3 Weeks',    days: 21 },
  { type: '1_month',    emoji: '🔥', label: '1 Month',    days: 30 },
  { type: '45_days',    emoji: '⚡', label: '45 Days',    days: 45 },
  { type: '2_months',   emoji: '🏅', label: '2 Months',   days: 60 },
  { type: '3_months',   emoji: '🎯', label: '3 Months',   days: 90 },
  { type: '100_days',   emoji: '💯', label: '100 Days',   days: 100 },
  { type: '4_months',   emoji: '🌊', label: '4 Months',   days: 120 },
  { type: '5_months',   emoji: '🦋', label: '5 Months',   days: 150 },
  { type: '6_months',   emoji: '💎', label: '6 Months',   days: 180 },
  { type: '200_days',   emoji: '🌈', label: '200 Days',   days: 200 },
  { type: '9_months',   emoji: '🌸', label: '9 Months',   days: 270 },
  { type: '1_year',     emoji: '🏆', label: '1 Year',     days: 365 },
  { type: '500_days',   emoji: '🔑', label: '500 Days',   days: 500 },
  { type: '18_months',  emoji: '🦅', label: '18 Months',  days: 548 },
  { type: '2_years',    emoji: '👑', label: '2 Years',    days: 730 },
  { type: '27_months',  emoji: '🕯️', label: '27 Months',  days: 821 },
  { type: '2_5_years',  emoji: '⚓', label: '2.5 Years',  days: 912 },
  { type: '1000_days',  emoji: '🎖️', label: '1000 Days',  days: 1000 },
  { type: '3_years',    emoji: '🌟', label: '3 Years',    days: 1095 },
  { type: '39_months',  emoji: '🌷', label: '39 Months',  days: 1186 },
  { type: '3_5_years',  emoji: '🧭', label: '3.5 Years',  days: 1278 },
  { type: '45_months',  emoji: '🌻', label: '45 Months',  days: 1369 },
  { type: '4_years',    emoji: '🔱', label: '4 Years',    days: 1460 },
  { type: '51_months',  emoji: '🦩', label: '51 Months',  days: 1551 },
  { type: '4_5_years',  emoji: '🎸', label: '4.5 Years',  days: 1643 },
  { type: '57_months',  emoji: '🌾', label: '57 Months',  days: 1734 },
  { type: '5_years',    emoji: '🦁', label: '5 Years',    days: 1825 },
  { type: '63_months',  emoji: '🐢', label: '63 Months',  days: 1917 },
  { type: '5_5_years',  emoji: '🦊', label: '5.5 Years',  days: 2008 },
  { type: '69_months',  emoji: '🌼', label: '69 Months',  days: 2099 },
  { type: '6_years',    emoji: '🌍', label: '6 Years',    days: 2190 },
  { type: '75_months',  emoji: '🍃', label: '75 Months',  days: 2281 },
  { type: '6_5_years',  emoji: '🦜', label: '6.5 Years',  days: 2373 },
  { type: '81_months',  emoji: '🍀', label: '81 Months',  days: 2464 },
  { type: '7_years',    emoji: '⚜️', label: '7 Years',    days: 2555 },
  { type: '87_months',  emoji: '🎋', label: '87 Months',  days: 2646 },
  { type: '7_5_years',  emoji: '🦢', label: '7.5 Years',  days: 2738 },
  { type: '93_months',  emoji: '🌺', label: '93 Months',  days: 2829 },
  { type: '8_years',    emoji: '🔮', label: '8 Years',    days: 2920 },
  { type: '99_months',  emoji: '🐋', label: '99 Months',  days: 3011 },
  { type: '8_5_years',  emoji: '🌏', label: '8.5 Years',  days: 3103 },
  { type: '105_months', emoji: '🪷', label: '105 Months', days: 3194 },
  { type: '9_years',    emoji: '🌠', label: '9 Years',    days: 3285 },
  { type: '111_months', emoji: '🦄', label: '111 Months', days: 3376 },
  { type: '9_5_years',  emoji: '🔭', label: '9.5 Years',  days: 3468 },
  { type: '117_months', emoji: '✴️', label: '117 Months', days: 3559 },
  { type: '10_years',   emoji: '💫', label: '10 Years',   days: 3650 },
];

export const BADGE_CELEBRATIONS = [
  { icon: '🎉', text: 'Congratulations!' },
  { icon: '💪', text: 'You actually did it.' },
  { icon: '🌅', text: 'A new chapter.' },
  { icon: '🔥', text: 'Unstoppable.' },
  { icon: '🥹', text: 'So proud of you.' },
  { icon: '⚡', text: 'That took real strength.' },
  { icon: '🌱', text: 'Look how far you\'ve come.' },
  { icon: '🏅', text: 'Hard-earned. Yours forever.' },
  { icon: '✨', text: 'This is what progress looks like.' },
  { icon: '🎯', text: 'You said you would. You did.' },
];

export const BADGE_EARNED_MSGS = [
  "Every day you hold on builds on this milestone. Keep going.",
  "You did what many never manage. Be proud of that.",
  "This badge is proof — you are stronger than the urge.",
  "Look how far you've come. The person you were would be amazed.",
  "This milestone is yours forever. No one can take it away.",
  "You showed up every single day to earn this. That's real strength.",
  "Each milestone is a promise you kept — to yourself.",
  "Recovery is built one day at a time. You're doing it.",
  "You proved that change is possible. Keep building on it.",
  "This is what commitment looks like. You should be proud.",
  "Not everyone who tries makes it this far. You did.",
  "This badge represents every urge you resisted. That's power.",
  "You chose yourself, again and again. That's what this means.",
  "The hardest part was deciding to start. You did that — and kept going.",
  "Every single day counted. Every single one.",
  "You are living proof that change is possible.",
  "Your future self is grateful for every day you held on.",
  "This is a real achievement. Don't let anyone tell you otherwise.",
  "You turned the corner. This badge marks the moment.",
  "Strength isn't the absence of struggle — it's showing up anyway. You did.",
];

export const CONFETTI_EMOJIS = ['✨', '⭐', '💫', '🌟', '💎', '✦', '✨', '⭐'];
